"use client";

import React, { useState, useEffect } from 'react';
import styles from '../revisions.module.css';

// Revisions Ranking Page (Weekly Price Surge)
interface WeeklyRankingItem {
    rank: number;
    ticker: string;
    name: string;
    change_pct: number;
}

export default function RevisionRankingPage() {
    const [ranking, setRanking] = useState<WeeklyRankingItem[]>([]);
    const [updatedAt, setUpdatedAt] = useState<string>('');
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        // Load static JSON generated by backend
        fetch('/data/weekly_ranking.json')
            .then(res => res.json())
            .then(data => {
                if (data.ranking) {
                    setRanking(data.ranking);
                    setUpdatedAt(data.updated_at);
                }
            })
            .catch(err => console.error("Failed to load ranking", err))
            .finally(() => setLoading(false));
    }, []);

    return (
        <main className={styles.container}>
            <header className={styles.header}>
                <h1 className={styles.title}>
                    🏆 今週の爆上げランキング
                </h1>
                <p className={styles.subtitle}>
                    今週、業績修正を発表した銘柄の中で<strong>株価上昇率が高かった銘柄</strong>のトップ20です。
                    <br />
                    <span style={{ fontSize: '0.8rem', opacity: 0.7 }}>更新: {updatedAt} (毎週土曜更新)</span>
                </p>
                <div style={{ marginTop: '1rem' }}>
                    <a href="/revisions" style={{ fontSize: '0.9rem', color: 'var(--accent)', textDecoration: 'underline' }}>
                        &larr; 修正一覧に戻る
                    </a>
                </div>
            </header>

            <section>
                <div className={styles.tableContainer}>
                    <table className={styles.table}>
                        <thead>
                            <tr>
                                <th>順位</th>
                                <th>コード</th>
                                <th>銘柄名</th>
                                <th>週間騰落率</th>
                            </tr>
                        </thead>
                        <tbody>
                            {ranking.map((item) => (
                                <tr key={item.ticker}>
                                    <td>
                                        <span style={{
                                            display: 'inline-block',
                                            width: '28px', height: '28px',
                                            background: item.rank <= 3 ? '#fbbf24' : '#334155',
                                            color: item.rank <= 3 ? '#000' : '#fff',
                                            borderRadius: '50%', textAlign: 'center', lineHeight: '28px',
                                            fontWeight: 'bold'
                                        }}>
                                            {item.rank}
                                        </span>
                                    </td>
                                    <td>
                                        <a href={`https://finance.yahoo.co.jp/quote/${item.ticker}.T`} target="_blank" rel="noopener noreferrer" className={styles.tickerLink}>
                                            {item.ticker}
                                        </a>
                                    </td>
                                    <td>{item.name}</td>
                                    <td style={{ fontWeight: 'bold', color: item.change_pct > 0 ? '#4ade80' : '#f87171' }}>
                                        {item.change_pct > 0 ? '+' : ''}{item.change_pct}%
                                    </td>
                                </tr>
                            ))}

                            {loading && (
                                <tr>
                                    <td colSpan={4} style={{ textAlign: 'center', padding: '2rem' }}>読み込み中...</td>
                                </tr>
                            )}

                            {!loading && ranking.length === 0 && (
                                <tr>
                                    <td colSpan={4} style={{ textAlign: 'center', padding: '2rem' }}>
                                        現在データ収集中です。<br />土曜日の朝10時に更新されます。
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </section>
        </main>
    );
}
